version: 1
disable_existing_loggers: true



formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

filters:
    infoFilter:
        (): logconfig.logconfig.infoFilter # path to class

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG # lowest level and above included
    formatter: standard
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logfiles/debug.log
    filters: [infoFilter]
    encoding: utf8
    backupCount: 20

  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: standard
    filename: logfiles/info.log
    backupCount: 4
    filters: [infoFilter]
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: WARN
    formatter: standard
    filename: logfiles/warn.log
    filters: [infoFilter]
    encoding: utf8
    backupCount: 20

  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: error
    filename: logfiles/errors.log
    filters: [infoFilter]
    encoding: utf8
    backupCount: 20

  critical_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: CRITICAL
    formatter: standard
    filename: logfiles/critical.log
    filters: [infoFilter]
    encoding: utf8
    backupCount: 20

root:
  level: DEBUG
  handlers: [console, debug_file_handler, info_file_handler, warn_file_handler, error_file_handler, critical_file_handler]
  propogate: yes