version: 1
disable_existing_loggers: true



formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"



handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logfiles/info.log

  # error_file_handler:
  #   class: logging.handlers.TimedRotatingFileHandler
  #   level: ERROR
  #   formatter: error
  #   filename: logfiles/errors.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  # debug_file_handler:
  #   class: logging.handlers.TimedRotatingFileHandler
  #   level: DEBUG
  #   formatter: standard
  #   filename: logfiles/debug.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  # critical_file_handler:
  #   class: logging.handlers.TimedRotatingFileHandler
  #   level: CRITICAL
  #   formatter: standard
  #   filename: logfiles/critical.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

  # warn_file_handler:
  #   class: logging.handlers.TimedRotatingFileHandler
  #   level: WARN
  #   formatter: standard
  #   filename: logfiles/warn.log
  #   maxBytes: 10485760 # 10MB
  #   backupCount: 20
  #   encoding: utf8

root:
  level: NOTSET
  handlers: [console, info_file_handler]
  propogate: yes